version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: icom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    restart: unless-stopped  
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
      - 6379:6379
    restart: unless-stopped  
  mongo:
    image: mongo
    volumes:
      - mongo_data:/var/lib/mongo/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    restart: unless-stopped    
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    ports:
      - 5672:5672
      - 15672:15672  
    restart: unless-stopped
volumes:
  postgres_data: {}
  mongo_data: {}
  redis_data: {}
  rabbitmq_data: {}